syntaxfm/website

- shows/001 - React Tools.md
* I added the links in the **Show notes** section, the Sick picks in the **Sick picks** section and the **Shameless Plugs** in it's corresponding section.
* I could not get or find the followings:
-- *B Boys tools* that Scott talks about.
-- Not sure if Wes was referring to [Hacker News Example in Next.js](https://github.com/now-examples/next-news)
-- *MediaR* ❔  Scott starts talking about it on minute 34..
> Added links. Still have a couple doubts (See description)

- shows/003 - CSS Preprocessors and Structuring CSS.md
Missing Easing Easy Ease Package. Couldn't find it.
> Update 003 - CSS Preprocessors and Structuring CSS.md

- pages/index.js
first of all: awesome new project. Thx! Looking forward to good podcast stuff!
made this pr following these "should i use component state?" conventions, which i think make good sense https://twitter.com/dan_abramov/status/749710501916139520.
also: in case "shows" data update those updates would not be shown without a reload as the initial state declaration in the constructor is only executed on component mount.
in case you like these modifications, feel free to pull.
> removed usage of component props to declare initial component state

- shows/003 - CSS Preprocessors and Structuring CSS.md
Broken link, had to fix it 😜  Great work with the podcast as mentioned before. Keep them coming. Cheers!
> Fixes broken link for RuckSack website

- components/Header.js
- pages/index.js
Fixed These issues as seen in the pictures. Nice Podcast Wes BTW.
> Fix https favicon issue and scott's Picture

- lib/getShows.js
Changed the renderer option as shown here : https://github.com/chjj/marked#renderer
> Added feature to open links from show notes in a new tab. 

- shows/011 - Productivity Hot Tips.md
> itesm -> items

- shows/011 - Productivity Hot Tips.md
small typo in shameless plug URL
> Update 011 - Productivity Hot Tips.md

- README.md
- package-lock.json
- styles/_bars.styl
Added clear instructions in the `Readme.md` about what version of Node to use. And there was some minor spacing inconsistencies in `_bars.styl`.
> changes to readme and spacing to _bars.styl.

- shows/012 -Why is Everyone Switching to VS Code.md
> Add Autorename Tag to Show Notes

- shows/028 - Async Await.md
Add https:// to wesbos.github.io/Async-Await-Talk/
> Update 028 - Async Await.md - Fix bad link

- shows/028 - Async Await.md
☝️ 
They were causing some parts to appear as links as-is.
> Update show notes to "code'ify" examples

- pages/sponsor.js
> fix typo in sponsor.js page

- shows/009 - JavaScript Utility Libraries.md
Someone's missing in the description 😛 Also Browsesync should be Browsersync but I missed that earlier
> Update 009 - JavaScript Utility Libraries.md

- shows/040 - Testing.md
> Unit testing done👨🏻‍💻Fixed Jest Link

- shows/045 - potluck.md
Changed the "JWP" text (2 places) to "JWT"
> 045-potluck.md

- shows/045 - potluck.md
It was written as JW**P**. Switch to JW**T**. Hope this helps!
> Fix JWT typo

- shows/047 - How to Get Better at Debugging.md
> 047 - Fix typo

- components/Header.js
- styles/_header.styl
For #71 .
Desktop
Mweb
Hover state:
> Adding Potluck Submission btn

- styles/_header.styl
- styles/_type.styl
Potluck Button was overlapping with tagline around 1000px
> Adjusted styling for Title so tagline and potluck BTN dont overlap

- components/Footer.js
I was listening to an episode and I don't know how, but I happened to notice Scott's last name was spelled incorrectly so I decided to fix it. 😅
> Fixing Scott's last name in the footer.

- shows/060 - The Undocumented Web.md
Fixed a spelling error so that the nitpickers (like myself) can rest easy at night.
> Fix spelling error

- shows/064 - Gear.md
The link to scott gears was mygear but the page live at my-gear
> Update page Gear.md - fix link for scott'Gear

- shows/068 - Design.md
Hi @wesbos! Just finished listening to episode 68 and jumped into the show notes for your Spotify playlist sick pick. The original playlist that was posted looks a bit older and hasn't been updated since 2013. I think I found the correct one in this PR.
🤘🔥
> Update 068 - /r/posthardcore Spotify playlist

- components/Player.js
- components/Show.js
- components/meta.js
- package-lock.json
- package.json
- styles/_show.styl
- styles/_variables.styl
> svg icons added and a11y issues fixed

- pages/sponsor.js
> add tweet to sponsor page

- shows/069 - Framer.md
Changed "Fist" to "First" -> Scott's Framer X First Look Video
> Corrected Spelling

- shows/080 - New JS.md
> Update 080 - New JS.md

- styles/_show.styl
This add some simple restyling to make scrolling on mobile more friendly.
> [Feature]: Make scrolling on mobile easier

- components/meta.js
- package.json
boosts the seo lighthouse score from 89 to 💯!
Signed-off-by: Logan McAnsh <logan@mcan.sh>
> add description meta tag for seo

- components/Footer.js
- components/Header.js
- components/ShowNotes.js
- components/Subscribe.js
- lib/getShows.js
https://developers.google.com/web/tools/lighthouse/audits/noopener
Signed-off-by: Logan McAnsh <logan@mcan.sh>
> adds rel attribute to links that open in new tabs

- .eslintrc
- components/Footer.js
- components/Header.js
- components/Page.js
- components/Player.js
- components/Show.js
- components/ShowList.js
- components/ShowNotes.js
- components/Subscribe.js
- components/bars.js
- components/meta.js
- lib/formatTime.js
- lib/getShows.js
- lib/timestamp-helper.js
- package-lock.json
- pages/index.js
- pages/sponsor.js
* added `.eslintrc` from https://github.com/wesbos/dotfiles/blob/master/.eslintrc
* Updated all the components as much as I could
TODO:
* remove all the eslint-ignore statements
> added eslint and formatted application

- components/meta.js
Demo of changes on Now:
https://syntax-vkvfpncwin.now.sh/
> add syntax-yellow as browser-bar color on chrome on android

- components/Header.js
[Proposal] It is common that logo is also an anchor that usually points to homepage. I was surprised when I clicked Syntax logo and nothing happened. Therefore I am proposing to add anchor on logo. 🙂
> Add anchor on logo to point to homepage

- components/meta.js
- lib/getBaseURL.js
- pages/index.js
- pages/sponsor.js
Output meta tags for shows only if show prop exists
> Fixes #218 create staticPage prop in meta.js

- README.md
- components/Footer.js
[Proposal] I suggest using `Link` on footer sponsorship anchor as well. 🙂
> Use Link on sponsor anchor

- shows/096 - Gift Guide.md
> Update 096 - Gift Guide.md

- shows/094 - Potluck.md
Supposedly, the channel's owner has accidentally deleted it:
> Welcome back at Jelle's Marble Runs!
> I accidentally deleted my channel, so i have to start over again. Fortunately, I still have all my videos in my archive so I will upload them over time.
> Update 094 - Potluck.md

- shows/101 - where are they now.md
Same typo of the previous week's episode. Hope you don't mind me highlighting it.
> fix contentful link

- lib/getShows.js
> Revert "Fix show date formatting"

- shows/110 - Balance.md
> Update 110 - Balance.md

- shows/108 - Potluck.md
Just removing a space and a random number.
> Update 108 - Potluck.md

- shows/120 - gatsby-vs-next.md
Wanted to fix The armoury Link, before it was linking to the TechMeme Podcast
> Fix to the 'Thearmoury" Link

- shows/108 - Potluck.md
Correcting the spelling of "Tidying Up" 
from "Tiding Up" to "Tidying Up"
> Correcting the spelling of "Tidying Up"

- shows/126 - bootcamps.md
MindNode was mentioned in the episode but not linked in the show notes
> adding MindNode to Links list

- shows/103 - where are they now part 2.md
Underescrore.js -> Underscore.js
> Fixed typo in "Underscore.js"

- shows/135 - cranky devs.md
I _needed_ to see this talk when Wes mentioned it and was sad to see it wasn't linked, so here it is.
> Added link to Getting Closure on Hooks by Swix

- package-lock.json
- shows/142 - travis neilson.md
The link to "How To Use Adobe XD" in shameless plugs was giving a 404 error.  Fixed it to go to levelup course
> fixed 404 error on How To Use Adobe XD link

- shows/150 - gatsby themes.md
- Shameless plugs links needed https://
- Jasons Twitch url was spelled wrong :)
> Updated links in Gatsby Themes shownotes

- shows/141 - async await.md
> Update 141 - async await.md

- shows/140 - potluck.md
The 6th question in episode 140 slips in at 24:01 not 20:49.
> Wrong Question time fixed

- shows/134 - live.md
1. Uncapitalize 'Data'
2. Change '_data_ jokes' to '_dad_ jokes'
> Fix typos in 134 - live.md

- shows/082 - New JS Part 2.md
I think some example might be helpful for someone like me which are not a native English speaker.
--
Big fan of Syntax.fm, thanks for providing so many useful information for us.
> 082 - add example for show note

- shows/150 - gatsby themes.md
> Fix typo in 150 - gatsby themes.md

- shows/155 - growth.md
> Update 155 - growth.md

- shows/082 - New JS Part 2.md
Sorry, 
My last PR https://github.com/wesbos/Syntax/pull/289 have some layout error, 
so I create this one to fix it.
---
> 082 - fix note format

- components/ShowNotes.js
- package-lock.json
- package.json
- styles/_show.styl
Fixes an issue with old episodes and show notes which is otherwise [solved/described by this userscript](https://gist.github.com/salembeats/8d1b73d2cf14ba012039ac844d0c79c6). Additionally, the scrollbar for the show notes resets to the top every time the show notes are updated.
**NOTE**: The React version is explicitly updated to 16.8.0 in `manifest.json` so that hooks can be used for the scrollbar-reset behavior.
> fixes for displaying show notes @ older episodes

- shows/161 - vscode.md
Super tiny thing I noticed but thought you might want to update the link to the documentation for Ctrl+Click - Go To Definition.
Love the podcast and the stuff you do guys!
> Updated to VSCode Ctrl+Click link

- components/Show.js
- styles/_show.styl
- styles/_variables.styl
Hey Wes and Scott,
I thought it would be useful to subtly differentiate between the different types of show.
Note, this is my first ever PR to any Open Source repo.
And this is my first time doing anything in React (I've been watching Scott's course 'React 16 For Everyone, and I've already bought your two React courses Wes!)
Love the show!
Cheers,
Adrian
> Added colour coding to the different type of show (Potluck, Hasty Treat, Regular)

- shows/181 - automating stuff.md
> Add Wes' Z recommendation

- shows/190 - WordPress.md
3:50 - Why did start Delicious Brains? -> 3:50 - Why did *Brad* start Delicious Brains?
Not sure why line 87 is shown to be changed ¯\_(ツ)_/¯
> Fixed description on ep 190

- shows/194 - potluck.md
change "tiny cms" to "tina cms" - as referenced in the show
> tina typo fix

- components/Show.js
- styles/_show.styl
Hello @wesbos , Here is the PR as requested [here](https://github.com/wesbos/Syntax/issues/449).
Thank you so much, and BTW, I'm a big fan of the show!
> changed date position to be on the same line with the episode number

- components/VolumeBars.js
Description
-----
Adds another bar to the volume of the Syntax web player 🤘🏻 so you can you know... turn it up to 11.
https://www.youtube.com/watch?v=4xgx4k83zzc
Testing
---
Check that I havent busted anything else along the way and that the volume still works as it should... just 11 is now the same as 10 but its 11 so its cooler.
> Turns the volume up to 11! 🤘🏻

- shows/223 - framer.md
Is this a mistake or is it intentional? 😁
> Fix in URL

- shows/224 - serverless.md
Same here.
Sorry for not putting it in 1 commit...
> Update 224 - fix in URL

- shows/228 - serverless.md
Added missing fauna db on links even though was on notes.
> Added missing fauna on links

- shows/250 - scott teaches wes.md
on page load was getting Uncaught SyntaxError: Unexpected token ','
was preventing show 250 from playing.
in MD file wrapped code in lines 29,30 in ticks
> updated MD for show #250 to fix unexpected token Issue

- shows/255 - slow connection 2.md
Idk why it just bothered me enough to do this!
> Updated typo for your sponsor

- shows/257 - scott goes linux.md
The app Scott uses is actually albert, so I changed the notes accordingly.
> Update 257 - scott goes linux.md

- shows/246 - bootcamps.md
> Fixed typo on line 25

- lib/getShows.js
> Fix Issue 545

- .vscode/settings.json
- components/Player.js
- components/Show.js
- components/ShowList.js
- components/VolumeBars.js
- components/bars.js
- components/meta.js
- lib/getShows.js
- next.config.js
- pages/200.js
- pages/_document.js
- pages/api/glob.js
- pages/show/[number]/[slug].js
- pages/sickpicks.js
- pages/sponsor.js
* formats with `npm run lint:fix`
* manually fixes un-auto-fixable issues
* adds `.vscode/settings.json` with settings from https://github.com/wesbos/eslint-config-wesbos#with-vs-code - will auto fix for people that don't have their settings configured globally on save
> Lint fixes and vscode settings

- shows/066 - React.md
Links are displayed as list items in other episode notes.
> Convert links to list items

- shows/282 - webdev past.md
> Fix: Typo fix in Title of Episode #282

- shows/300.md
Hey, noticed my name was misspelled on the show notes. I fixed that and updated the links.
> updated links, name, and added twitter profile for me.

- package-lock.json
- shows/300.md
Thanks for having me on Episode 300!
> Update Brad Garropy's show notes

- shows/304 - potluck.md
Fixes a small typo on the timestamp: 45:17 instead of 47:17.
> update timestamp of question on episode 304

- shows/308 - gatsby.md
Changed gone to done in line 20. Possible typo
> Update 308 - gatsby.md

- shows/310 - severless.md
blink-155 rebranded to 155 pod so link needs to be updated
> Fix link to Been Here For Too Long

- shows/144 - side hustles.md
After listening to this podcast twice I went on the hunt for Courtland's Validation Checklist. He shared it on Indie Hackers a while back. Not sure if someone needs to check with him first on adding this. I'll tweet him and tag everyone in it 😎
> Update 144 - side hustles.md

- shows/358 - react-typescript.md
The first snippet isn't rendering properly and therefore the following ones are messed up:
Not sure if that's the proper fix actually...
> Fix snippet in shownotes for episode 358

- shows/407 - new laptops.md
- shows/408 - troubleshooting.md
Ready for publishing I believe. :)
> 407 / 408 episodes

- shows/332 - desk setups.md
I believe your countertop is 8-feet and not 8-inches.
> Change to single quote, to mean feet

- shows/418 - 2021 In Review.md
Fixed Remix link in Show Notes in line 34.
> Update 418 - 2021 In Review.md

- shows/419 - JS One Liners.md
Formatting was incorrect on the website.
> Update 419 - Remove erroneous backtick.

- shows/425 - Updating Project Dependencies.md
Hey Wes!
Just found this typo.
Cheers
> Fix: 425 - Fix typo - Dependancies

- shows/426 - Monorepos.md
> Fix: Fix typo 426 Monorepos

- shows/429 - Pros and Cons of JavaScript Servers.md
Good to go so long as the Hashnode sponsor copy for the show notes is good to go.
> added 429 details

- components/ShowNotes.js
Not my best work, but hey it works
> Fix Issue 691

- shows/432 - Potluck.md
> fix: Correct typo in Episode 432 show notes

- shows/463 - Supper Club Tom.md
> Title Typo Fix

- shows/463 - Supper Club Tom.md
> Update 463 - Supper Club Tom.md

- shows/484 - Supperclub .md
Show notes had "Developers from Mutual Liberty" instead of "Liberty Mutual"
> Swap Mutual and Liberty

- shows/486 - Code styles.md
> Updated with new shameless plugs section

- shows/511 - Supper club.md
MP3 updated, episode notes needs FireHydrant copy
> added firehydrant sponsor

- shows/517 - supper Brian.md
> Update 517 - supper Brian.md

- shows/557 - Tasty TypeScript.md
> added 557 mp3

- shows/619 - supper braum.md
> added episode number to front matter

- shows/624 - tasty typescript.md
Hey guys,
Probably not really worth a PR but there's a typo in Wes's BSKY profile. :)
> Update 624 - tasty typescript.md

- shows/508 - supperclub.md
> Update 508 - supperclub.md

- shows/670 - Supper Tolinski.md
removed supper club from title
> Updating title structure to new format

- src/styles/base.css
> Bring back italics and bold buttons

- package.json
- pnpm-lock.yaml
- prisma/schema.prisma
- src/routes/(site)/admin/+layout.server.ts
- src/routes/webhooks/ai/+server.ts
- src/server/ai/openai.ts
- src/server/auth/access_token.ts
- src/server/transcripts/deepgram.ts
- src/server/transcripts/flagger.ts
- src/server/transcripts/transcripts.ts
- vercel.json
- why_do_i_need_this.mjs
Fixed https://github.com/syntaxfm/website/issues/1175
> Get FFMpeg WASM and Transcripts working on Vercel

- src/lib/transcript/Transcript.svelte
- src/server/ai/queries.ts
- src/server/transcripts/utils.ts
> stop loading of transcript words as it is too large

- src/utilities/slug.ts
little util function for creating a show slug since we use it in 2 spots now.
> add slug util

- src/lib/Pagination.svelte
- src/lib/ShowCard.svelte
- src/styles/variables.css
>  better dark mode on mobile

- src/lib/transcript/Transcript.svelte
- src/routes/(site)/show/[show_number]/[slug]/[[tab]]/+page.svelte
> remove transcript utterance from transcript display

- src/routes/(site)/show/[show_number]/[slug]/[[tab]]/+page.svelte
- src/state/player.ts
> handle timestamp clicks when audio isn't already playing

- src/lib/FacePile.svelte
> fallback face for missing github avatars

- src/lib/Pagination.svelte
- src/routes/(site)/shows/+page.server.ts
- src/routes/(site)/shows/+page.svelte
Fixes this use case: https://github.com/syntaxfm/website/issues/1245
> fixes pagination issue where you can end up on a page with no shows

- shows/679 - supper Chris.md
added: guest, name, of, github, twitter, url
> Add guest metadata

- shows/142 - travis neilson.md
I [heard the call](https://x.com/wesbos/status/1716884755416035618) and happen to be both a fan of the pod and looking for my last Hacktoberfest contribution so here is the guest metadata for Episode 142 with Travis Neilson! Related: #1267
> Add guest metadata to episode 142

- src/styles/base.css
fixes https://github.com/syntaxfm/website/issues/1265
> fix ios font size jump

- src/lib/transcript/Transcript.svelte
- src/routes/(site)/admin/shows/[show_number]/+page.svelte
- src/routes/(site)/show/[show_number]/[slug]/[[tab]]/+page.svelte
Fixes https://github.com/syntaxfm/website/issues/1294
> change shows if nessecary when clicking transcript timestamp

- src/routes/(site)/guest/[name_slug]/+page.server.ts
> Fix guest face not showing up on guest page show card

- package.json
- pnpm-lock.yaml
- src/hooks.server.ts
> adds profiling and performance sentry

- package.json
- src/hooks.server.ts
- src/routes/(blank)/og/[number]/+page.server.ts
- src/routes/(site)/show/[show_number]/[slug]/[[tab]]/+page.server.ts
- src/routes/api/shows/[number=show_number]/+server.ts
- src/server/shows.ts
Completes https://github.com/syntaxfm/website/issues/1324
> tunes up a number of the db queries

- src/lib/player/Player.svelte
- src/routes/(site)/about/+page.svelte
not worth it, too many bug reports
> Remove fun easter egg

- shows/700 - supper payload.md
Adds jmikrut github username to show 700.
> chore: adds guest jmikrut username for show 700

- package.json
- pnpm-lock.yaml
- src/lib/PodcastHero.svelte
- src/routes/(site)/Header.svelte
This needs @stolinski to publish a new version of https://github.com/leveluptuts/svelte-side-menu/pull/2 yet
> fix accesiblilty warning in svelte

- src/routes/api/shows/+server.ts
- src/routes/api/shows/[number=show_number]/+server.ts
- src/routes/api/shows/latest/+server.ts
- src/routes/api/shows/query.ts
> change API to only provide future shows

- .vscode/settings.json
- src/lib/Icon.svelte
- src/lib/hosts/HostSocialLink.svelte
- src/routes/(site)/+page.server.ts
- src/routes/(site)/Footer.svelte
- src/routes/(site)/guests/+page.server.ts
- src/routes/(site)/guests/+page.svelte
- src/routes/(site)/show/[show_number]/[slug]/+layout.server.ts
- src/routes/(site)/show/[show_number]/[slug]/transcript/+page.server.ts
- src/routes/(site)/shows/+page.server.ts
- src/routes/(site)/shows/+page.svelte
> SEO / Search Console Improvements. Includes Guest Page, Shows Page, filtering

- src/routes/(site)/guest/[name_slug]/+page.server.ts
fixes https://github.com/syntaxfm/website/issues/1455
> sort shows by most recent on guest page

- shows/704 - tasty.md
git element -> getElement
prospective element -> perspective element
it's -> its
dropped unmatched paren
pseudo-element and -class use dashes on MDN
Also - the transcript for this episode appears to be cut off somewhere around minute 13.
> Update 704 - tasty.md - various small fixes for the show notes

- src/lib/NewsletterForm.svelte
- src/lib/newsletter/NewsletterLogo.svelte
- src/routes/(site)/snackpack/+page.server.ts
- src/routes/(site)/snackpack/+page.svelte
- src/routes/(site)/snackpack/[issue_id]/+page.server.ts
New header
Light theme
Dark theme
> Set titles for snackpack urls + logo on landing page

- src/lib/ShowCard.svelte
> Fix missing contract on show card play button (fixes #1449)

- src/state/player.ts
Fixes https://github.com/syntaxfm/website/issues/1481 and more.
> Fixes playback issues when changing episode or starting new after finishing

- src/routes/(site)/about/+page.server.ts
> Add missing await in count_shows

- src/routes/(site)/shows/+page.server.ts
Covering: https://github.com/syntaxfm/website/issues/1442
Simply a quick promise all settled and the required checks for the results.
> Use Promise.allSettled for shows query and count query

- shows/730 - Own Your Own PaaS.md
- src/routes/(site)/admin/shows/[show_number]/+page.svelte
- src/routes/(site)/admin/shows/[show_number]/Dump.svelte
- src/server/shows.ts
when the frontmatter url is updated, it doesnt update the DB. this fixes that
> Fix: updated markdown frontmatter url

- package.json
- pnpm-lock.yaml
- src/server/transcripts/deepgram.ts
- src/server/transcripts/transcripts.ts
The main reason the transcript request was timing out was that the mp3 files were too large, but while I was debugging, I realized the DB saves could be done concurrently - to a point. This implements that using p-map
> Transcript save perf

- shows/730 - Own Your Own PaaS.md
> Update 730 - Own Your Own PaaS.md

- src/lib/player/Player.svelte
- src/lib/share/HairButton.svelte
- src/routes/(blank)/embed/[show_number]/+page.svelte
- src/routes/(site)/show/[show_number]/[slug]/+layout.svelte
Why? https://github.com/syntaxfm/website/issues/1563
> Share → Hair

- src/lib/transcript/TableOfContents.svelte
- src/lib/transcript/Transcript.svelte
fixes https://github.com/syntaxfm/website/issues/1258
> Fixes mobile layout issues on the transcript page

- src/hooks.client.ts
> removes masking from session replays

- src/styles/base.css
- src/styles/layout.css
> adds overflow-wrap anywhere

- package.json
- pnpm-lock.yaml
- src/routes/(blank)/og/[show_number].jpg/+server.ts
> upgrades puppeteer, corrects types for headless chrome

- shows/746 - Infrastructure for TS Devs.md
> Update 746 - Infrastructure for TS Devs.md

- src/styles/themes/hail.css
> Adds Hail Theme

- src/const.ts
> Remove Google Podcasts

- README.md
* Added a table to README with how to get other environment variables
> chore: add info on where to get env vars

- src/app.html
- vercel.json
This fix proxies analytic events through the site's domain so they are not blocked by ad blockers / trackers.
> Proxy plausible analytics - fixes #1625

- shows/751 - UI Components.md
Added [Ariakit](https://ariakit.org).
> Add Ariakit to 751 - UI Components.md

- shows/751 - UI Components.md
Add a component widgets library (AgnosUI) providing both Headless components and Bootstrap ones.
> Update 751 - UI Components.md

- static/tiktokpU03MmT2Zmu6CI4nggzZ3xrPnT3TktFV.txt
* Created a tiktok org / app to access their API for video analytics.
* Need to verify our domain.
> add tiktok verification

- src/lib/newsletter/NewsletterForm.svelte
> removes conditional for base newsletter layout

- src/server/shows.ts
Need to debug why the show isn't importing in prod, but is locally.
> logging for show import

- src/lib/newsletter/SwaggyNewsletterForm.svelte
This is mostly just to test the codecov integration https://github.com/syntaxfm/website/pull/1709
> removes unused logos from newsletter signup

- shows/609 - Tasty Syntax giveaway.md
fixes https://github.com/syntaxfm/website/issues/1671
> fix date for episode 609

- package.json
- pnpm-lock.yaml
- src/routes/(site)/snackpack/[issue_id]/+page.server.ts
- src/routes/(site)/snackpack/[issue_id]/+page.svelte
- src/routes/(site)/style.css
the global styles of the newsletter were leaking out to the website
> style overrides for newsletter embed

- prisma/schema.prisma
- shows/779 - Why SQLite is Taking Over with Brian Holt & Marco Bambini.md
- shows/781 - Potluck - The Value of TypeScript × Vue vs Svelte × Leetcode.md
- shows/782 - The Developer’s Guide To Fonts with Stephen Nixon.md
- shows/786 - What Open Source license should you use.md
- shows/787 - You Should Try Vuejs.md
- shows/788 - Supabase with Paul Copplestone.md
- shows/789 - Do More With AI - LLMs With Big Token Counts.md
- src/lib/HostsAndGuests.svelte
- src/lib/PodcastHero.svelte
- src/lib/ShowCard.svelte
- src/routes/(blank)/embed/[show_number]/+page.server.ts
- src/routes/(blank)/embed/[show_number]/+page.svelte
- src/routes/(site)/show/[show_number]/[slug]/+layout.server.ts
- src/routes/(site)/show/[show_number]/[slug]/+layout.svelte
- src/server/ai/queries.ts
- src/server/shows.ts
Allows host overrides and adds CJ to the hero.
> Cj ification

- src/routes/(blank)/og/[show_number_or_title]/ShowOg.svelte
* Shows hosts if present in OG image
> fix: Update hosts in OG image

- shows/742 - Potluck: Migrating to Typescript, Semver Explained, Accurate Timers and Countdowns.md
- shows/744 - Docker For Developers.md
* Adding myself as host to 2 older episodes
> add cj as host to episodes

- package.json
- pnpm-lock.yaml
Fixes annoying side menu warning.
> updates side-menu

- pnpm-lock.yaml
- src/routes/(site)/show/[show_number]/[slug]/+layout.svelte
- start_script/src/main.rs
> fixes issue where timestamps were breaking player

- README.md
- docker-compose.yml
* Adds redis / redis http for cache testing locally without upstash
> add redis to docker compose

- src/lib/meta/Meta.svelte
makes it discoverable. Can test with https://rssfeedasap.com/
> Adding RSS meta tag to website

- src/routes/(site)/admin/shows/[show_number]/+page.server.ts
- src/routes/(site)/admin/shows/[show_number]/+page.svelte
* This adds a form to the admin show page that allows updating of AI generated title and description.
* Fixes #1721
> feat: allow edit of AI generated title and description

- package.json
version bump seems to be broken.
https://github.com/syntaxfm/website/actions/runs/10355734580/job/28664038979
maybe this fixes it?
> manually bump version

- .github/workflows/playwright-tests.yml
- .github/workflows/svelte_check.yml
- shows/99999 - Test.md
* If the only changes in a commit are to a markdown file in the `shows` directory
* Do not run playwright tests or svelte check
> update actions to ignore shows

- shows/828 - Loggingin Verification: Magic Links, 2FA, SMS Codes.md
> Create - (828 - Loggingin Verification: Magic Links, 2FA, SMS Codes.md)

- shows/826 - YouNeed These 30 Apps - PART 2.md
> Create - (826 - YouNeed These 30 Apps - PART 2.md)

- .github/workflows/svelte_check.yml
- src/lib/FormWithLoader.svelte
- src/lib/forms/UserSubmissionAction.ts
- src/lib/forms/validateTurnstileToken.ts
- src/routes/(site)/admin/submissions/+page.server.ts
- src/routes/(site)/admin/submissions/+page.svelte
> Submissions management UI. Filtering, delete, updating etc..

- shows/834 - AIWill Improve Your Web Development Workflow.md
> Create - (834 - AIWill Improve Your Web Development Workflow.md)

- prisma/schema.prisma
- src/lib/forms/UserSubmissionForm.svelte
- src/routes/(site)/oss/+page.server.ts
- src/routes/(site)/oss/+page.svelte
This needs a Schema PR because I added a new value to the enum.
> OSS Pledge page WIP

- src/routes/(site)/admin/submissions/+page.server.ts
- src/routes/(site)/admin/submissions/+page.svelte
> Pass prisma enums to client

- src/lib/ShowCard.svelte
> fix show card number overlap

- shows/837 - YouShould Drop Express and Try Hono.md
> Create - (837 - YouShould Drop Express and Try Hono.md)

- shows/826 - YouNeed These 30 Apps - PART 2.md
Add missing link to cross platform alternative to Klack which was mentioned in the episode.
> Update 826 - YouNeed These 30 Apps - PART 2.md

- shows/838 - ProductivityTools for Web Developers.md
> Create - (838 - ProductivityTools for Web Developers.md)

- shows/843 - TalkingEVs: Range Anxiety, Charging, and Tech.md
> Create - (843 - TalkingEVs: Range Anxiety, Charging, and Tech.md)

- shows/840 - SpookyWeb Dev Horror Stories - PART 1.md
> Create - (840 - SpookyWeb Dev Horror Stories - PART 1.md)

- shows/843 - Copilot Kills Cursor Reacting to Github Universe Keynote.md
> Create - (843 - Copilot Kills Cursor Reacting to Github Universe Keynote.md)

- .cursorrules
Don't open until xmas (after we upgrade to Svelte 5)
> Adds svelte 5 cursor rules

- shows/847 - Syntax Holiday Gift Guide.md
> Create - (847 - Syntax Holiday Gift Guide.md)

- shows/852 - Safe Server Exposure with Cloudflare Tunnels.md
> Create - (852 - Safe Server Exposure with Cloudflare Tunnels.md)

- shows/855 - Fast Websites The New Speculation Rules API.md
> Create - (855 - Fast Websites The New Speculation Rules API.md)

- shows/854 - Motion with Matt Perry.md
> Update 854 - Motion with Matt Perry.md

- src/server/auth/users.ts
> add randy to admin users

- shows/856 - Loading UIs Rust Webpack New Cookie Types Conference Talks  More.md
> Create - (856 - Loading UIs Rust Webpack New Cookie Types Conference Talks  More.md)

- shows/858 - How to Go Deeper With Your Learning.md
> Create - (858 - How to Go Deeper With Your Learning.md)

- shows/859 - Streaming Video in 2025.md
> Create - (859 - Streaming Video in 2025.md)

- shows/862 - Svelte 5.md
> Create - (862 - Svelte 5.md)

- shows/863 - 2024 A Year in Review.md
> Create - (863 - 2024 A Year in Review.md)

- shows/864 - Durable Objects Tab State Hacks and Headless CMS Choices.md
> Create - (864 - Durable Objects Tab State Hacks and Headless CMS Choices.md)

- shows/865 - CSS Performance  Rate Limiting  Array Sort Behavior  STUMPd.md
> Create - (865 - CSS Performance  Rate Limiting  Array Sort Behavior  STUMPd.md)

- shows/867 - Zero Sync.md
> Create - (867 - Zero Sync.md)

- shows/871 - Coding Agents Cursor  Windsurf Tips.md
> Create - (871 - Coding Agents Cursor  Windsurf Tips.md)

- shows/875 - JavaScript Signals Explained.md
> Create - (875 - JavaScript Signals Explained.md)

- shows/877 - Tailwind 4.md
> Create - (877 - Tailwind 4.md)

- shows/879 - Fullstack Cloudflare.md
> Create - (879 - Fullstack Cloudflare.md)

- shows/881 - What Happened to Remix Worth Using Axios Client Only Nextjs.md
> Create - (881 - What Happened to Remix Worth Using Axios Client Only Nextjs.md)

- shows/883 - Web Vitals Explained.md
> Create - (883 - Web Vitals Explained.md)

- shows/885 - CSS Fonts Fallbacks Variable and Trimming.md
> Create - (885 - CSS Fonts Fallbacks Variable and Trimming.md)

- shows/889 - Planning A Build.md
> Create - (889 - Planning A Build.md)

- .stylelintrc.json
- src/lib/ProducedBySentry.stories.svelte
- src/lib/ProducedBySentry.svelte
- src/lib/ShowCard.svelte
- src/lib/ShowTable.svelte
- src/lib/Tabs.svelte
- src/lib/hosts/Host.svelte
- src/lib/newsletter/NewsletterForm.svelte
- src/lib/schedule.svelte
- src/lib/search/SearchResults.svelte
- src/lib/transcript/TableOfContents.svelte
- src/lib/transcript/Transcript.svelte
- src/routes/(blank)/embed/[show_number]/+page.svelte
- src/routes/(blank)/links/+page.svelte
- src/routes/(blank)/og/[show_number_or_title]/ShowOg.svelte
- src/routes/(site)/MobileNav.svelte
- src/routes/(site)/admin/shows/[show_number]/+page.svelte
- src/routes/(site)/guests/+page.svelte
- src/routes/(site)/show/[show_number]/[slug]/+layout.svelte
- src/routes/(site)/show/[show_number]/[slug]/+page.svelte
- src/routes/(site)/style.css
- src/styles/Buttons.stories.svelte
- src/styles/Buttons.svelte
- src/styles/bass.css
- src/styles/buttons.css
- src/styles/reset.css
- src/styles/typography.css
- src/styles/utilities.css
- src/styles/variables.css
Adds the base css, utilities, vars, ect. Will most likely need tweaking as we good. 
I called it Bass because it's funny on a few levels. Sorry.
> BASS 🔊 CSS

- shows/893 - Everyone Is Talking About MCP.md
> Create - (893 - Everyone Is Talking About MCP.md)

- shows/895 - React Server Components Where are we at.md
> Create - (895 - React Server Components Where are we at.md)

- shows/897 - Making Your App Feel Faster Than It Really Is.md
> Create - (897 - Making Your App Feel Faster Than It Really Is.md)

- shows/901 - JS News New React  Svelte APIs RSC Updates Redwood and Storybook.md
> Create - (901 - JS News New React  Svelte APIs RSC Updates Redwood and Storybook.md)

- shows/903 - You Should Learn Nuxt.md
> Create - (903 - You Should Learn Nuxt.md)

- shows/905 - You Should Learn Nuxt.md
> Update 905 - You Should Learn Nuxt.md

- shows/909 - Handling and Throwing Errors.md
> Create - (909 - Handling and Throwing Errors.md)

- shows/911 - Browsers in 2025 Whats up with Arc Dia Firefox Chrome and Opera GX.md
> Create - (911 - Browsers in 2025 Whats up with Arc Dia Firefox Chrome and Opera GX.md)

- shows/913 - NEWS Remix drops React Safari 26 CSS  mega fast Vite and TypeSCript.md
> Create - (913 - NEWS Remix drops React Safari 26 CSS  mega fast Vite and TypeSCript.md)

- shows/915 - 200mo Background Agents CLI Tooling and Max Mode.md
> Create - (915 - 200mo Background Agents CLI Tooling and Max Mode.md)

- shows/919 - Better Auth with Better Auth.md
> Create - (919 - Better Auth with Better Auth.md)

- shows/921 - AI Coding Roadmap for Newbies And Skeptics.md
> Create - (921 - AI Coding Roadmap for Newbies And Skeptics.md)

- shows/923 - Getting the Most Out of AI Coding.md
> Create - (923 - Getting the Most Out of AI Coding.md)

- shows/926 - RSS Is NOT Dead.md
> Update 926 - RSS Is NOT Dead.md

- shows/927 - AI Browsers 100X Build Speed Massive Svelte Update  Web Dev News.md
> Create - (927 - AI Browsers 100X Build Speed Massive Svelte Update  Web Dev News.md)

- shows/929 - Cloudflare Blocks AI Crawlers  Debugging Local Data  Raising Kids with Healthy Digital Habits and More.md
> Create - (929 - Cloudflare Blocks AI Crawlers  Debugging Local Data  Raising Kids with Healthy Digital Habits and More.md)

- shows/933 - Hackweek Overview  What Is It What Did We Build.md
> Create - (933 - Hackweek Overview  What Is It What Did We Build.md)

- shows/943 - Modern React with Ricky Hanlon React Core Dev.md
> Create - (943 - Modern React with Ricky Hanlon React Core Dev.md)

- src/server/transcripts/flagger.ts
* Always use full path to flagger audio file
> Fix fetch transcript
