syntaxfm/website

styles/_show.styl
Removed max-height and overflow scroll from _show.styl, which will fix [issue 32](https://github.com/wesbos/Syntax/issues/32)
=> removed max-height and overflow scroll from _show.styl

components/Player.js, pages/index.js
This solves issue [#42](https://github.com/wesbos/Syntax/issues/42).
As Next.js renders React components on the server-side, I had to use `if (typeof window !== 'undefined') {
` to have access to the `window` object. Functionality works as expected, however the console prompts a `React attempted to reuse markup in a container but the checksum was invalid.` upon initial page load which I am unsure on how to fix.
Big thanks to @ollie1700 for helping with this PR.
I hope this helps! 🔥
=> Adding localStorage to last played points on podcasts

shows/041 - BURNOUT.md
Spellcheck. PS, the Wikipedia link still worked, only the text was misspelled.
=> Change locus ON control to locus OF control

shows/049 - potluck.md
Fixed spelling and capitalization of sponsor.
=> Changed Cofeecup to CoffeeCup in Update 049 - potluck.md

components/Player.js, styles/_player.styl
Currently, the volume level inputs are being hidden using `display: none`. This makes them inaccessible for screenreader users and those navigating the site with their keyboard since the element is not being rendered. 
To fix this, I added an `sr-only` class which will completely hide an element visually and makes it not take up any space, but will allow it to be screenreader and keyboard accessible. Now the inputs can be focused and hitting the left and right arrows will turn the volume up and down, respectively. 
Some screenreaders also seem to not read content when `font-size: 0` is used, so I wrapped the volume label text in `span`s with the `sr-only` class which fixes the issue.
For the play/pause button, I also added an `aria-label` attribute which changes based on the state, since …
=> Add accessibility to volume controls

lib/formatTime.js
Fixed bug when timer shows ****:60** seconds
=> Fixed numbers in formatTime

styles/_player.styl
Fixes #128 Used focus-within pseudo class on player volume section to show outline ring when focusing on volume labels.
Also added keyboard shortcuts to control volume and other things in PR #130 .
=> Fixes #128, add focus to volume UI

pages/sponsor.js
This suppresses a couple "Invalid DOM property" warnings
=> sponsor.js: camel case two attributes for React

styles/_person.styl
Hey guys, love the show. I was looking for a way to contribute to syntax.fm and felt the font size in the header bios way a bit too small to be easily readable.
On desktop, increasing the font size caused the bio to wrap around the avatar in a not-very-nice way, so I made some minor tweaks to account for this too. Hope it's a useful (if small) addition.
=> Increased font size and tweaked layout in header bios

components/Player.js, styles/_player.styl
I often find myself jumping to a specific time based on the show keynotes but since there is no way to see at which time I am hovering over, I can only make a guess. So I added a tooltip on the player progress bar to view the time while hovering over it.
Here's a demo gif to view the change:
=> Show time in tooltip while hovering over the player progress bar

styles/_player.styl, styles/_subscribe.styl, styles/style.styl
Subscribe links outline color on focus was set to black, which was invisible against the black background. Updated to theme yellow.
Also, volume div was set to the webkit default blue while its sibling elements were set to the theme yellow. Updated to theme yellow.
This is a resubmission of PR #210 
@416serg
=> Fix outline colors on subscribe links and volume div for accessibility

styles/_show.styl
Fixes issue https://github.com/wesbos/Syntax/issues/215.
Makes overflow rules more verbose and sets overflow-x to auto so the horizontal scrollbar only appears if it's needed just in case.
I didn't include changes to package-lock.json in the commit, I hope that's ok?
=> Remove horizontal scroll bar on show listings

components/meta.js
to avoid "undefined – Syntax Podcast"
=> More gracefully handle missing title

lib/getShows.js
The latest episode (105: Hasty Treat - CSS and JS Pointer Events) currently has an episode date of Dec 31st, 2019 on all my devices (all set to UTC+0):
Pull Request #87 included a fix for a bug(?) in `date-fns` but per some testing I think this is now causing the incorrect date to show up and the old formatting string (`MMM Do, YYYY`) results in the correct behaviour.
=> Fix show date formatting

components/Player.js, components/VolumeBars.js
Reference: [Issue #234](https://github.com/wesbos/Syntax/issues/234) 😄
The playbackRate and Volume setting are now both placed in LocalStorage. That logic lives in Player.js.
I also made a few additional changes. Previously, Player.js had 10 hardcoded input + label tags that represented the volume bars. I refactored this, by creating a new component called VolumeBars.js. Now Player.js displays the volume bars ( `<VolumeBars volume={this.volume} />` ) via the VolumeBars.js imported component.
VolumeBars.js now generates these same 10 input/label blocks with the same unique attribute settings they each had before. The benefit is I generated these 10 blocks by just mapping over one as a template in the VolumeBars.js component. Now this better follows the DRY (don't repeat yourself) principal …
=> Persist playbackRate and volume property

shows/120 - gatsby-vs-next.md
=> Fixed silly typo, it's `use` not `us`

shows/140 - potluck.md
The previous links directed toward a github 404 page, perhaps looking for a local page.
```diff
--   wesbos.com/courses
++ https://wesbos.com/courses
```
Scott's plug also refers to its pro page. I don't know if it is intentional, but the particular series "Animating React" is found at [this url](https://www.leveluptutorials.com/tutorials/animating-react).
=> fix links to shameless plugs

shows/168 - Blogging.md
Dev.to link was going to Crunchbase, not dev.to
=> Dev.to link fix

shows/161 - vscode.md
=> Fix spelling of SynthWave

shows/181 - automating stuff.md
Scott gave a tip about removing node_modules recursively in Episode 181. He sent me this solution in a DM on Twitter.
=> Remove node_modules tip in Episode 181

components/Header.js
Change the source of the Avatars to Github. Pictures download faster from github - Often on slow Connection Scott's avatar loads faster than Wes's
(and use github's size feature to deliver smaller images)
=> GitHub avatars

components/Page.js
* Currently implements the same injection inside `meta.js` - moving over to `_document.js` in https://github.com/wesbos/Syntax/pull/423
Less html to load, more perf 🚀
=> removes duplicate style injection

components/Player.js, components/Show.js, components/ShowList.js, components/bars.js, pages/index.js
The current code manipulates the dom directly to have achieve animating the "hifi bars" in the showlist when the podcast player is playing. This is not idiomatic react.
This changes fixes that by lifting "isPlaying" up into the parent component (`IndexPage`) and then propegating it down to the `Bars` component.
=> Remove direct DOM manipulation 💩

package-lock.json
The package-lock.json was removed in https://github.com/wesbos/Syntax/pull/458. Because of that, `npm install` no longer works: `eslint` is not compatible with the Node.js version that is set in the `engines` field.
=> Add package-lock.json back

shows/224 - serverless.md
PR #466 seems to have broken the download URL for this episode via an incorrect "." placement.
This commit just moves it to the correct location to fix the URL so that it no longer results in a 404 on the website.
=> Fixing "." placement in download URL

shows/215 - uses.md
weserv.nl is the correct domain.
Love y'all's podcast! Have a nice day. :)
=> Replace webserv.nl with weserv.nl

shows/241 - 5 more things.md
The description is set by using dangerouslySetInnerHTML, and as it was encountering only opening <script> tag it is showing an error and stopped parsing. This is causing incomplete description. 
Instead of using <script>, just replaced it with text content script.
The description abruptly stops at - where should I put.
=> Resolved issue of description breaking due to <script>

lib/getShows.js, pages/show/[number]/[slug].js, shows/262 - react wish list.md
The shows are now filtered inside `getStaticProps` instead of `getStaticPaths`, allowing not released shows to be revalidated.
Also did a change to the upcoming show to make sure it doesn't output invalid HTML.
=> Revalidate new shows

lib/getShows.js
The `Edit Show Notes` links are leading to GitHub 404 pages. This is related to using `process.cwd()`.  I'm not sure of the intended purpose of the commit this PR reverts, but this should get things back into working order. 👍 
**Current Prod URL:** https://github.com/wesbos/Syntax/edit/master//var/task/shows/271%20-%20upgrading.md
**Local URL Example:** https://github.com/wesbos/Syntax/edit/master//Users/ryan/Desktop/Syntax/shows/271%20-%20upgrading.md
**Working URL:** https://github.com/wesbos/Syntax/edit/master/shows/271%20-%20upgrading.md
=> Fix - Update Broken Edit Show Links

components/ShowNotes.js
This updates the show notes edit url to redirect to the edit page on GitHub.
The link for the `Edit Show Notes` had a stale URL, this PR updates it to have the `/shows` in the path to fix it.
Go to the Vercel deploy preview (https://syntax-git-fix-show-notes-url.wesbos.vercel.app) and click on `Edit Show Notes` under an episode show, you should be redirected to the edit page on GitHub instead of a 404.
https://twitter.com/syntaxfm/status/1319040265882116099
=> fix: update show notes edit url

shows/290 - potluck.md
I would like to propose updating the link to Angular from the old v1 AngularJS
site to the new v10 Angular site (angular.io) in the show notes for episode 290.
=> Update show notes link to Angular

shows/306 - gift guide.md
Fixed the Amazon link of Sony WH1000XM4  which was wrongly linked to Vivo Pneumatic Mic Arm.
Shamelessly changed it to my affiliate link but feel free to fix it to yours.
Anyways, Merry Christmas!! 🎄
=> fix: update show notes link (ep306)

styles/_button.styl
Moved margin to right side - simplified _button.styl and fixed alignment on narrower screens (mobile or narrow desktop views)
Buttons in `ShowNotes` component were misaligned in narrower screens due to left margin. 
Margin moved to right side to allow for simpler .styl file and proper alignment in narrow/mobile views
=> fix: :iphone: moved margin to align on smaller screens

shows/322 - deno.md
Github source for standard library seems to have moved to its own repository: https://github.com/denoland/deno_std
=> Fix Deno standard library Github link

styles/_header.styl
On Firefox Linux header links were a bit off:
Apparently the `font-weight: 100` was not handled as in Chrome. Anyway removing it looks good in Chrome, Chromium and Firefox:
=> fix: removed font-weight: 100 from header links

shows/520 - Supper with Nikolas Burke.md
Fixes: #818
Episode 520 has `number: 484` in the frontmatter, and causes issues with playback of the original episode 484.
After changing the number to 520, and recompiling the site, I was able to play both episodes on my local machine (see screenshots of the before/after below).
Before:
After:
=> Updated episode number to 520 instead of 484

shows/430 - Creator of Wordle.md
Hi! Jon from Sanity here. Noticed that `/create` leads to an old starter page – updated it to our current `/get-started` page.
=> Update Sanity URL

package.json
Tools that autodetect node versions (like nixpacks on @flightcontrolhq) use the package.json field to choose which node version to use. Node 14 is very old and npm install fails with it.
This updates engines field to use v18 which is the current node LTS version.
=> Update package.json node engines to latest LTS version (node 18)

shows/619 - supper braum.md
Episode 619 was missing the `number` field in the frontmatter.
=> Add missing `number` to show 619

shows/616 - adam CSS.md
Add link to transitions on discrete properties
This change adds a link to the Chrome status issue on the feature change to support transitions on specified discrete properties.
I'm not entirely sure this is the correct link, but I couldn't find anything else related on the matter.
=> Update 616 - adam CSS.md

src/routes/(site)/[show_number]/+page.server.ts
This PR fixes #1174 by changing the route parameter `[number=show_number]` to just `[show_number]`.
Also fixes a small typo which was causing an error to be thrown when redirecting for invalid `show_number` values.
=> Fix show number redirects

src/lib/PodcastHero.svelte, src/lib/ProducedBySentry.svelte, src/lib/page_loading_indicator.svelte, src/routes/(site)/+layout.svelte, src/routes/(site)/Footer.svelte, src/utilities/slug.ts
=> Page Loading Indicator

src/actions/anchor.ts
Correct calculations for anchor svelte-action for `RIGHT` and `BOTTOM`
=> Corrections on positioning in anchor.ts

src/params/ThemeMaker.svelte
I think this will fix  https://github.com/syntaxfm/website/issues/1251
=> removes regex lookbehind, not compatible with safari < 16.3

src/routes/(site)/+layout.server.ts
the og image has a port in the URL, which means it's not showing up.
=> remove port from OG image URL

src/lib/ListenLinks.svelte, src/routes/(site)/show/[show_number]/[slug]/[[tab]]/+page.svelte
The links in the show actions are have titles which get used as fallback for the accessible name, but it's better to be explicit (and more terse, since context informs the text as well)
=> Add explicit accessible names to show actions

src/styles/base.css
- Fixes a typo: `*:before-`
- Fixes a comment typo
- Removes an unneeded selector, because `[href^=http]` [matches both](https://codepen.io/bartveneman/pen/gOqMeWx?editors=1100) http and https links
=> fix some tiny CSS things

src/routes/(site)/Footer.svelte
External footer links don't open new tab. Was listening to an episode while browsing the site, I went to come check the source code out...and well I lost my spot in the episode since the link didn't open in a new tab. Hopefully this is a simple fix :)
=> add target attribute in Footer.svelte to external links

src/hooks.server.ts
Fixes #1393
I notice in other parts of the code, we check if `redis` is non-null so I think this is ok?
=> Don't initialize Redis if no credentials

package.json
npm is using [`node-semver`](https://github.com/npm/node-semver) to check the version of the engines. For example https://github.com/npm/cli/blob/86ac76caa4a8bd5d1acb1777befdbc4d9ebc8a1a/docs/bin/build.js#L3C1-L3C1.
They are also using [caret ranges](https://github.com/npm/node-semver#caret-ranges-123-025-004) for engines. See https://github.com/npm/cli/blob/latest/package.json#L266.
=> Use caret ranges for engines

src/routes/(site)/Header.svelte, src/routes/(site)/MobileNav.svelte
From index:
I made some style tweaks so that the nav fits when ~700-900px (tighten the pill padding by a few pixels, reduce the gap between pills, etc):
When visiting `/snackpack`:
=> Add newsletter to nav links

src/routes/(site)/guests/+page.svelte
Add some lazy loading and explicit image dimensions in case CSS fails. Should save ~7MB when loading the page. I picked 10 images for eager loading because on desktop 2 rows of 5 images are initially visible. Mobile shows 2 or 4 images initially.
=> Improve image loading on guests page

src/lib/search/SearchResultList.svelte
In the search modal's recent searches, every show number is shown as `undefined`. 
This is because in recent searches, the variable `result` has the type `Block & Show`, but in the normal search results, `result` has the type `Tree`.
After the fix:
=> Fix missing show number in recent searches

src/lib/search/SearchBox.svelte
Fixes the issue #1472 by adding right padding to a search input so that text is not overlapped by a close button.
=> Fix #1472. Update search input's right padding.

src/lib/search/SearchBox.svelte
Small accessibility defect in CSS when using "outline: none" was fixed. Made simple changes following best practices to prevent users with higher contrasts from experiencing bugs when using the tab key to select buttons, inputs, etc. Reference: https://www.youtube.com/shorts/4B_4WLpbyp8
=> Accessibility Suggestion

src/lib/FacePile.svelte, src/lib/ShowOg.svelte
Fixes #1479 
This does a couple things:
* Adds margin-bottom to the face pile + syntax logo to push that content up (note this also moves the h1 title text up a bit)
* Adds a `text-shadow` outline to the `h1` title text in case it overlays the yellow show number
* Makes the face pile avatars bigger (`120px`)
* Increases the gap between the face pile avatars (this also affects other pages, e.g. regular web show cards)
* Removes the "grit" texture mask from the datetime and avatars
At 1200x630:
=> Tweak OG card design to accomodate x/twitter title overlay

shows/713 - supper Eric.md
Fixes #1484 (Hopefully)
I am not sure whether or not this wrong timecode exists anywhere else, or is it only present in a .md file. If you could check it, that would be great as the `pnpm db:seed` seeds database only to 705th show, so there is no way (that I'm aware of) to check the 713th episode
=> Change show 713 sick picks timecode

src/routes/(site)/pages/[page]/+page.server.ts
Fixes #1430 
Use the processor's ``process`` async function instead of ``processSync`` to parse markdown non-blockingly
=> Async Processor processing in Markdown Pages

src/lib/ShowCard.svelte, src/routes/(site)/show/[show_number]/[slug]/+layout.svelte
Fixes #1432 
This treatment uses CSS variables + `color-mix` and I've verified it with light and dark themes.
Before:
After:
=> Make show title + description more accessible by adding contrast

prisma/schema.prisma
Deleting (and I guess Querying) relational content (Transcript → Utterance → Word) was timing out on PlanetScale because it was taking longer than 20s to run the query.
Turns out it's because Prisma in `relationMode = "prisma"` doesn't actually create the foreign keys and PlanetScale doesn't support that. So there were no indexes and made the queries super slow - essentially had to load the entire table and then .filter() it. 
adding indexes makes it much much much faster. This PR does that to the schema, but I also will need to PR them in planetscale.
=> adds indexes to relational content

src/styles/buttons.css
While working on Wallace's custom property inspector I found there's a typo in `--body-font-familly`. The inspector shows there _is_ a custom prop called `--body-font-family` so I changed the typo to that one.
=> Fix typo in `--body-font-familly`

src/lib/search/search.ts
FWIW I did look into alternatives, such as using remark, but since this is a webworker there is no access to the document 😢.
Best I can do is this regex appraoch. 
before:
after:
=> feat: strip markdown links in search

src/lib/ShowCard.svelte
Refs #1359 
The goal of this PR is to let users see more shows when scrolling through the default route or `/shows` on mobile.
Changes in this PR:
- Put faces + play button on same row
- Hide card descriptions at small viewport width
- Reduce show number font size at small viewport width
- Add some shadow to the date text to help contrast when overlapping w/ date (happens at small viewport width)
Before (note only 2 cards visible):
After:
Note some design changes in this PR affect other non-mobile layouts, e.g. this layout now has the facepile + play button on the same row:
=> Improve card layout/readability on small viewports (mobile)

src/lib/theme/variable_color_svg.ts, src/params/ThemeMaker.svelte, src/routes/(blank)/embed/[show_number]/+page.svelte, src/routes/(site)/+layout.svelte, src/routes/(site)/show/[show_number]/[slug]/+layout.svelte, src/state/theme.ts
I simplified the theme setting and switching to be entirely serverside. Optimistic UI just via dom api and className. A super simple solutions that makes themes way more reliable and less obtuse. 
I was hotpotatoing the theme state from client to server and there was opportunity for them to become not always nsync. Just took client state out of the picture all together with a dom update.
=> Theme serverification

src/routes/(site)/show/[show_number]/[slug]/+layout.server.ts, src/routes/(site)/show/[show_number]/[slug]/+page.svelte, src/utilities/cache_mang.ts
Fixes https://github.com/syntaxfm/website/issues/1446
Also moves @stolinski's cache mang comments into JSDoc format so they show up on hover.
=> Adds pre + next links to each episode

src/lib/ShowCard.svelte, src/routes/(blank)/og/[show_number_or_title]/ShowOg.svelte
Passing ISO format to ensure valid datatime attribute value is being used. 
Closes #1588
=> Update Time element (#1588)

src/routes/(site)/+layout.svelte
when switching themes, we remove the svelte created unique class - thus the .theme-wrapper styles aren't applied until a full refresh. 
These variables need to be global, and not with a generated class name. 
Fixes #1584
=> fix global variables with theme switcher

scripts/merging-show-validation.js
* Cancels URL validation requests that take longer than 2 seconds
* Retries requests with a GET instead of HEAD in case of weird server behavior
=> fix(1637): create timeout and retry for md url validation

src/app.html, src/hooks.server.ts, src/routes/api/57475/3v3n7/+server.ts, src/routes/api/57475/script.js/+server.ts, vercel.json
* Before, the plausible events were proxied via the `vercel.json` which would only work when deployed to vercel or when running `vercel dev` locally
* Now, the events are proxied through custom API routes, so they will work in dev and when deployed
=> chore: move plausible proxy to api routes

src/app.html, vercel.json
* TLDR: we lost about 2 days worth of analytics because some users of the site are hitting a cached back-end function that doesn't have the updated proxy code
* [This error](https://syntax-fm.sentry.io/issues/5146658009/?query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=3) showed up in sentry
* The error `Could not parse content as FormData.` happens when the [hooks.server.ts](https://github.com/syntaxfm/website/blob/main/src/hooks.server.ts#L110) does not have the updated safe_form_data handle to skip parsing the body as form-data
* I'm baffled that a back-end function can be cached like this but I guess that's something that can happen on vercel?
* I'm reverting my proxy changes to go back to the `vercel.json` file for now
=> bug: revert plausible analytics change

src/lib/FacePile.svelte, src/lib/ShowCard.svelte
Some updates to the show card. The face pile was pushing the button to the right. The downside of 1fr 1fr columns in grid.
=> address face pile with 4+ guests at certain container sizes

src/app.html, src/hooks.server.ts, src/routes/api/57475/3v3n7/+server.ts, src/routes/api/errors/+server.ts, src/routes/api/optionsHandler.ts, vercel.json
* Reverts to using API functions for plausible analytics
* Updates `src/hooks.server.ts` to only call `form_data` if the content-type is form-data AND wraps the call in a try catch
* Any other type of POST request that comes into the app will 404 instead of failing to parse
* Updates plausible API function to forward error to Sentry if the call to plausible fails
* Updates sentry API function to include error message if proxy to sentry fails
* Adds OPTIONS request to both plausible and sentry proxy
* There were a few 404s in the logs for clients that were trying OPTIONS before making a POST request
=> chore: add error handling and options requests

shows/652 - Supper.md
As part of my other pull request, I noticed some invalid frontmatter errors in the console.
=> fix(652): correct invalid frontmatter

shows/751 - UI Components.md
- adds [drab](https://drab.robino.dev) to other component libraries. drab is a custom element that just provides JS without shadow DOM. Elements can be server-side rendered since users provide the HTML.
=> Update 751 - UI Components.md - Add drab component library

src/lib/transcript/Transcript.svelte, src/server/transcripts/transcripts.ts
This is a partial fix for #1193
=> fixes transcript parts being hidden

README.md, package.json, pnpm-lock.yaml, scripts/preheat.js
* Adds `dotenv-expand` so I can use this syntax in my `.env`:
```sh
DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
```
* Adds `pnpm db:push` to the preheat script to create the schema in the DB before seeding
=> add dotenv-expand; add create/update to preheat

src/routes/(blank)/og/[show_number].jpg/+server.ts, src/routes/(site)/show/[show_number]/[slug]/+page.server.ts, src/routes/(site)/show/[show_number]/[slug]/transcript/+page.server.ts, src/routes/(site)/sickpicks/+page.server.ts, src/routes/(site)/snackpack/+page.server.ts
Looks like its `max-age` for private cache. `s-maxage` for shared.
=> fixes incorrect shared cache max age header

src/routes/content.json/+server.ts
Been blowing through our "fast" bandwidth on vercel because this file isn't cached. Easy fix.
=> adds cache header to search content.json

src/hooks.server.ts
fixes #1749
Not sure when or how but for some reason contentType no longer includes "form-data". I added actions checks in "sk-form-data": "^2.0.2" which now makes sure you are using a svelte action before attempting to parse form data.
=> Fix form data

src/lib/share/HairButton.svelte
Fixes #1751
Just wraps navigator in a try/catch because cancelling throws.
https://stackoverflow.com/questions/60510383/web-share-api-navigator-share-problem-when-canceling-share-dialog-ios-and-androi
=> fixes abort error from sharing

src/hooks.server.ts, src/server/cache/cache_mang.ts
* This disables automaticDeserialization in the upstash client (the default is to just use JSON.parse)
* Calls JSON.parse manually when pulling from the cache
* adds a reviver function to convert the dates during parse
=> simplify date parse from cache

src/routes/(site)/show/[show_number]/[slug]/+layout.svelte, src/state/player.ts
* This is a partial fix for #1384  - I did not add anything to jump to the player, just improved the button functionality
* This fixes the player button on the show page
* If the episode is already playing, pressing the play button will pause the episode
* If the episode is paused, the button will say "resume"
* If the site is freshly loaded to a show page that the user was last listening to, the button will say "resume"
=> fix: #1384 - player button press when playing

package.json
[`npm-run-all2`](https://github.com/bcomnes/npm-run-all2) is a community fork of [`npm-run-all`](https://github.com/mysticatea/npm-run-all), which sadly hasn't had updates for over 5 years. 
I started the fork because I use `run-{p,s}` everywhere and wanted to see its ongoing maintenance continued. We're at 40k public repos adopting the fork so far, and are a designated replacement package in renovate bot. The plan for the fork is to keep maintaining the project pretty much as is for the foreseeable future. 
I'm sending out a few PRs to notable repos that I spot to see gauge interest on switching over.
It's a drop in replacement (same bin names) so this should be all you need to do to switch over. 
Love the podcast! Feel free to close if you aren't interested as well.
=> Update to npm-run-all2

src/routes/robots.txt/+server.ts, static/robots.txt
Instead of manually submitting your sitemap to Google, Bing & other search engines in the future; you can reference it in the robots.txt file as outlined on [Google here](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#addsitemap)  and [here](https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt#sitemap)
As far as I know it's followed by all search engines crawler; here is another [Bing](https://www.bing.com/webmasters/help/Sitemaps-3b5cf6ed) documentation
Since I had to use the PUBLIC_URL variable I moved it from static folder to be server generated (with a long cache).
=> refactor: :mag: move robots.txt to integrate the sitemap

src/hooks.server.ts, src/routes/(site)/admin/+layout.server.ts, tests/default.test.ts
Checking for admin privileges in the layout loader does not prevent the action from running as loaders run after the action. It must be checked in the action itself. To avoid duplicating for every action I've added it as a hook instead.
This does not test the actual admin role or a positive check that the action does run for admin. To do that we would need to create a session and it seems like the database does not get reseeded on each test run.
=> Check for admin privileges

shows/826 - YouNeed These 30 Apps - PART 2.md
Clipy was some screen recording tool, not the clipboard manager mentioned in the ep.
SVG Grabber was another one than the one Wes showed, and did not work for me.
Also fixed odd spelling of Magnet tiles/Magna-tiles/whatever.
=> Fixed links linking to wrong shit

src/routes/(site)/show/[show_number]/[slug]/+layout.svelte
This pull request updates the naming convention for downloaded podcast files to be more descriptive. Previously, files were named like `Syntax_-_812.mp3`, which did not provide information about the episode content. The new format matches the one used in the "Now Playing" widget on the website, making it easier for users to identify each episode.
=> Updated Naming Convention for Downloaded Podcast Files

src/hooks.server.ts, src/lib/search/search.ts, src/routes/(site)/[...number]/+page.server.ts, src/routes/(site)/show/[...all]/+page.server.ts, src/routes/content.json/content.server.ts
=> Improves Search and Show Number Find

src/lib/ShowCard.svelte
not sure how this broke, but the show numbers were not showing. 
Also needed to add relative to the date for Firefox stacking order.
=> reinstate show numbers on show cards

src/lib/forms/UserSubmissionAction.ts, src/lib/forms/UserSubmissionForm.svelte, src/lib/forms/userSubmissionSchema.ts, src/routes/(site)/admin/submissions/+page.server.ts, src/routes/(site)/admin/submissions/+page.svelte, src/routes/(site)/oss/+page.server.ts, src/routes/(site)/potluck/+page.server.ts, src/routes/(site)/spooky/+page.server.ts
This PR uses the Prisma DB enum both for the Zod validation and the admin filter dropdowns. Should make adding new types of submissions easy. 
Also migrated all files I touched to snake_case
=> Use Prisma enum for Zod validation and Admin filters

shows/844 - TypeScript Branded Types Streaming vs Polling  More.md
=> Create - (844 - TypeScript Branded Types Streaming vs Polling  More.md)

scripts/merging-show-validation.js, shows/853 - The State of Frontend.md, src/lib/PodcastHero.svelte, src/lib/player/Visualizer.svelte, svelte.config.js
=> Create - (853 - The State of Frontend.md)

shows/861 - Local Data Sqlite LocalStorage Session Cookies and IndexDB.md
=> Create - (861 - Local Data Sqlite LocalStorage Session Cookies and IndexDB.md)

shows/866 - 2025 Web Development Predictions.md
=> Create - (866 - 2025 Web Development Predictions.md)

src/lib/search/SearchBox.svelte
Svelte state is a proxy, and since we need to pass that to worker.postMessagae to log a recent search, it was breaking. 
Thanks to @hudochenkov and @s-petey  for the report + fix. 
https://github.com/syntaxfm/website/issues/1931
=> Converts svelte state to snapshot before passing to postMessage API

shows/869 - Node  TypeScript in 2025.md
=> Create - (869 - Node  TypeScript in 2025.md)

src/lib/search/Search.svelte
Fix a style issue where the ⌘ and K characters in the search bar were mismatched heights.
Before this fix:
After this fix:
=> Make ⌘ and K characters in search bar the same height

shows/939 - Creator of Vite Evan You.md
=> Create - (939 - Creator of Vite Evan You.md)

src/server/transcripts/flagger.ts
* Update flagger audio paths to be import assets so they are included in the build
=> Fix fetch transcript
